add typing-extensions to list of dependencies
feedzai/feedzai-altair-theme pull request #10
Opened 2022-06-15 13:44 UTC by biamalveiro

Hey! 😄 

I installed the theme with`pip install feedzai-altair-theme` and when I tried to enable it with `alt.themes.enable("feedzai")` I got an error`ModuleNotFoundError: No module named 'typing-extensions`. Seems that it is need in `types.py` and we are missing it in the dependencies in `setup.py`.

https://github.com/feedzai/feedzai-altair-theme/blob/529618a250ae57269df69e1226639cbc26376002/feedzai_altair_theme/types.py#L20

This pull request would just add it to the list of dependencies 📦

2022-06-15 20:33 UTC, joaopalmeiro requested changes
Thank you for this, @biamalveiro! Since the dependency is now in setup.py, can you remove it in Pipfile and generate a new lock file please? I can do it too, if you're short on time.

2022-06-20 07:33 UTC, biamalveiro commented on setup.py
> +DEPENDENCIES: List[str] = ["altair==4.*", "typing-extensions==4.*"]
Of course! ✅

2022-06-20 07:34 UTC, biamalveiro commented
Thanks for the feedback! I've made the suggested changes and generated a new lock file :)

2022-06-20 07:45 UTC, joaopalmeiro commented
> Thanks for the feedback! I've made the suggested changes and generated a new lock file :)

Thanks, @biamalveiro! 😄 

One more thing, which I completely forgot to say, sorry! Can you also update the `CHANGELOG.md` file and bump the package version in the `__init__.py` file, please (since we need to release a new package version with this update)? Proposal for the `CHANGELOG.md` file:

```
## [1.1.0] - 2022-06-20

### Fixed

- Add `typing-extensions` as a package dependency.
```

2022-06-20 08:56 UTC, joaopalmeiro approved these changes

2022-06-20 08:57 UTC, joaopalmeiro commented
It's perfect! I'll merge it, thanks again! 😄

2022-06-20 08:57 UTC, merged